' Tentukan path file BAT
Dim batFilePath, batFile
Set fso = CreateObject("Scripting.FileSystemObject")
batFilePath = fso.GetAbsolutePathName(".") & "\process.bat"

' Membuat file BAT
Set batFile = fso.CreateTextFile(batFilePath, True)

' Menulis isi file BAT
batFile.WriteLine "@echo off"
batFile.WriteLine "set ""install_dir=%CD%"""
batFile.WriteLine "set ""source=%install_dir%\temp\home"""
batFile.WriteLine "set ""exe=%install_dir%\temp\zip\7-Zip.exe"""
batFile.WriteLine "set ""backup_dir=%install_dir%\backup"""
batFile.WriteLine "set ""file="""""
batFile.WriteLine "set ""original_name="""""
batFile.WriteLine ""
batFile.WriteLine ":: Mengecek koneksi internet dengan ping"
batFile.WriteLine "echo Mengecek koneksi internet..."
batFile.WriteLine "ping -n 1 google.com >nul 2>nul"
batFile.WriteLine "if errorlevel 1 ("
batFile.WriteLine "    set message=Tidak ada koneksi internet. Silakan periksa koneksi Anda."
batFile.WriteLine "    call :msg"
batFile.WriteLine "    goto :cleanup"
batFile.WriteLine ")"
batFile.WriteLine ""
batFile.WriteLine ":: Lanjutkan proses download jika ada koneksi"
batFile.WriteLine "curl -L https://github.com/arv-fazriansyah/updateVBA/archive/refs/heads/main.zip -o updateVBA.zip || goto :error"
batFile.WriteLine "tar -xf updateVBA.zip --strip-components=1 ""updateVBA-main/*"" || goto :error"
batFile.WriteLine "del updateVBA.zip"
batFile.WriteLine ""
batFile.WriteLine ":: Menyembunyikan folder temp setelah ekstraksi"
batFile.WriteLine "attrib +h ""%install_dir%\temp"""
batFile.WriteLine ""
batFile.WriteLine ":: Mencari file Excel (.xlsb) di direktori instalasi"
batFile.WriteLine "for %%i in (""%install_dir%\*.xlsb"") do ("
batFile.WriteLine "    set ""file=%install_dir%\%%~nxi"""
batFile.WriteLine "    set ""original_name=%%~nxi"""
batFile.WriteLine "    goto :file_found"
batFile.WriteLine ")"
batFile.WriteLine ""
batFile.WriteLine ":: Notify if no Excel file is found"
batFile.WriteLine "set message=Simpan terlebih dahulu file RBK disini: %install_dir%"
batFile.WriteLine "call :msg"
batFile.WriteLine "goto :cleanup"
batFile.WriteLine ""
batFile.WriteLine ":file_found"
batFile.WriteLine ":: Membuat folder backup jika belum ada"
batFile.WriteLine "if not exist ""%backup_dir%"" ("
batFile.WriteLine "    mkdir ""%backup_dir%"""
batFile.WriteLine ")"
batFile.WriteLine ""
batFile.WriteLine ":: Membackup file Excel ke folder backup"
batFile.WriteLine "echo Membackup file:"
batFile.WriteLine "xcopy ""%file%"" ""%backup_dir%\\"" /Y"
batFile.WriteLine ""
batFile.WriteLine ":: Notify that backup is complete"
batFile.WriteLine "set message=File berhasil dibackup ke folder backup."
batFile.WriteLine ":: call :msg"
batFile.WriteLine ""
batFile.WriteLine ":: Mengecek apakah 7-Zip terpasang"
batFile.WriteLine "IF EXIST ""%ProgramFiles%\7-Zip\7z.exe"" ("
batFile.WriteLine "    rem echo 7-Zip sudah terpasang."
batFile.WriteLine ") ELSE ("
batFile.WriteLine "    echo 7-Zip belum terpasang. Sedang menginstal..."
batFile.WriteLine "    echo."
batFile.WriteLine "    :: Instalasi 7-Zip dalam mode diam"
batFile.WriteLine "    ""%exe%"" /S || goto :error"
batFile.WriteLine "    :: Notify that 7-Zip has been installed"
batFile.WriteLine "    set message=7-Zip telah terinstal."
batFile.WriteLine "    REM call :msg"
batFile.WriteLine ")"
batFile.WriteLine ""
batFile.WriteLine ":: Proses kompresi file menggunakan 7-Zip"
batFile.WriteLine "start /min """" ""%ProgramFiles%\7-Zip\7z.exe"" a ""%file%"" ""%source%\*"" || goto :error"
batFile.WriteLine ""
batFile.WriteLine ":: Notify that the file update was successful"
batFile.WriteLine "set message=File berhasil diupdate!"
batFile.WriteLine "call :msg"
batFile.WriteLine ""
batFile.WriteLine ":: Rename file setelah update"
batFile.WriteLine "set ""new_name=update_%original_name%"""
batFile.WriteLine "ren ""%file%"" ""%new_name%"" || goto :error"
batFile.WriteLine ""
batFile.WriteLine ":cleanup"
batFile.WriteLine ":: Menghapus folder temp setelah selesai atau jika ada error"
batFile.WriteLine "if exist ""%install_dir%\temp"" ("
batFile.WriteLine "    rmdir /s /q ""%install_dir%\temp"""
batFile.WriteLine ")"
batFile.WriteLine ""
batFile.WriteLine ":end"
batFile.WriteLine "exit"
batFile.WriteLine ""
batFile.WriteLine ":error"
batFile.WriteLine "set message=Terjadi kesalahan."
batFile.WriteLine "call :msg"
batFile.WriteLine "goto :cleanup"
batFile.WriteLine ""
batFile.WriteLine ":msg"
batFile.WriteLine ":: Create and run a VBS script for the message box and sound"
batFile.WriteLine "set tempPath=%temp%\msgbox.vbs"
batFile.WriteLine "echo Set objShell = CreateObject(""WScript.Shell"") > %tempPath%"
batFile.WriteLine "echo objShell.Popup ""%message%"", 0, ""Pemberitahuan"", 64 + 4096 >> %tempPath%"
batFile.WriteLine "echo objShell.SoundPlay ""SystemHand"" >> %tempPath%"
batFile.WriteLine "cscript //nologo %tempPath%"
batFile.WriteLine "del %tempPath%"
batFile.WriteLine "goto :eof"

' Tutup file BAT
batFile.Close

' Menjalankan file BAT secara tersembunyi
Dim objShell
Set objShell = CreateObject("WScript.Shell")
objShell.Run "cmd /c " & Chr(34) & batFilePath & Chr(34), 0, True

' Hapus file BAT setelah selesai
fso.DeleteFile batFilePath
